# Generated by Django 4.0.2 on 2022-06-29 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, verbose_name='Название теста')),
                ('subject', models.CharField(max_length=20, verbose_name='Предмет')),
                ('krypto', models.CharField(max_length=30, verbose_name='Криптоключ')),
                ('variants', models.IntegerField(verbose_name='Количество вариантов')),
                ('date', models.DateField()),
                ('author', models.CharField(max_length=30, verbose_name='Создатель')),
                ('contains', models.TextField(verbose_name='Содержание (ответы, вопросы...)')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
    ]
