# Generated by Django 4.0.2 on 2022-06-29 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otveti', '0002_alter_answers_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='author',
            field=models.CharField(max_length=500, verbose_name='Создатель'),
        ),
        migrations.AlterField(
            model_name='answers',
            name='krypto',
            field=models.CharField(max_length=300, verbose_name='Криптоключ'),
        ),
    ]
