# Generated by Django 4.0.2 on 2022-06-29 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otveti', '0004_alter_answers_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название теста'),
        ),
    ]
